// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { Application } from '@hotwired/stimulus'
import Sortable from 'stimulus-sortable'
import NestedForm from 'stimulus-rails-nested-form'

const application = Application.start()
application.register('sortable', Sortable)
application.register('nested-form', NestedForm)
import NestedRondoController from "./nested_rondo_controller"
application.register("nested-rondo", NestedRondoController)
